### PR TITLE
Set OptimizedAccessorFactory.noOptimization=true by default

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Review by lukasj — COMMENTED** [review]
What problem on which JDK is this trying to resolve? In all cases I've seen on JDK 11+ so far was that the caller did not support multi-release jar files (ie Ant <=1.10.6); in such case using `-Djdk.util.jar.enableMultiRelease=force` is the way to go

**Comment by jimma** [comment]
@lukasj I see there is a huge performance decrease in jaxb 2.3.3 with jdk8 with this default value  `OptimizedAccessorFactory.noOptimization=false` . From my local test, I don't see  there is some performance improvement with this  optimization and JDK11. So I think it's better set this value as true as it's backward compatible and faster on different JDK versions.

**Comment by lukasj** [comment]
Since JDK 9, this is off by default (noOptimization is true). Can you share a testcase showing the decrease on JDK8?

**Comment by jimma** [comment]
@lukasj  Can you please point me the source code to set this off (noOptimazation is true) by default since JDK9 ?

**Comment by lukasj** [comment]
see the [Injector](https://github.com/eclipse-ee4j/jaxb-ri/blob/EE8/jaxb-ri/runtime/impl/src/main/java-mr/9/com/sun/xml/bind/v2/runtime/reflect/opt/Injector.java) which does nothing and is supposed to be used

**Comment by jimma** [comment]
Thanks @lukasj .  
> Can you share a testcase showing the decrease on JDK8?

I pushed the test case project for the performance issue with JDK8: https://github.com/jimma/jaxb233perfmance . The steps to reproduce this issue are listed on README. Please check.

**Comment by jimma** [comment]
@lukasj  Did you get time to look at the producer ? The optimization change in jaxb 2.3.3. makes creates JAXBContext instance 10 times slower than jaxb 2.3.2.

**Comment by lukasj** [comment]
yup, you're right. Anyway, correct way to fix it is to just remove the code completely instead of setting variable to null - that can be done via system property even now

**Comment by jimma** [comment]
OK. @lukasj , I reverted this change with https://github.com/eclipse-ee4j/jaxb-ri/pull/1533. Please review.

**Comment by lukasj** [comment]
superseded by #1533

**Pull request closed without merging**
