### PR TITLE
Drop curl for external settings

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by lukasj** [comment]
I can’t afford having 2 hours window for getting artifacts from the mirror after they get out, see https://travis-ci.community/t/disable-google-maven-central/5301

**Comment by pzygielo** [comment]
Then
1. have empty `settings.xml`, as there is no need to redefine jakarta repos
2. have that `settings.xml` file in this Eclipse's repository, and not in project-external location.

**Comment by lukasj** [comment]
> Then
> 
> 1. have empty `settings.xml`, as there is no need to redefine jakarta repos
> 2. have that `settings.xml` file in this Eclipse's repository, and not in project-external location.

... and apply and maintain the same, likely temporary file which is to go away/become unused in a few weeks, in >15 more repositories. I do not think I'm willing to do that. What I need right now is something allowing me to get from 1st repo to the last in less than a day while not having to run all tests and checks locally and not breaking anything.

**Comment by pzygielo** [comment]
Thanks for sharing. All comments together are quite different than initial

> travis mirrors everything through some global mirror, so whatever is set in project poms, is by passed

**Comment by lukasj** [comment]
> travis mirrors everything through some global mirror, so whatever is set in project poms, is by passed

travis is apparently evolving ;-)

**Pull request closed without merging**
