### PR TITLE
Fix incorrect header for package javax.xml.catalog in OSGi manifest file

### PR DESCRIPTION
**Pull request by pieterjanpintens**
Signed-off-by: Pieter-Jan Pintens <pieter-jan.pintens@unifiedpost.com>

### CODE REVIEW

**Comment by pieterjanpintens** [comment]
It should be fine now, also fixed the other spot where the headers were wrong

**Comment by pieterjanpintens** [comment]
Are you going to build another 2.3.3 version soon? We are trying to move to Java 11 and this breaks our CI build.

**Comment by lukasj** [comment]
this needs to go master, not to different branch; 2.3.3-b03 will be created from there. As for when - in January

**Comment by pieterjanpintens** [comment]
OK changed it to master, is there a way we can test this in advance (get the jar) to mitigate the risk of something else being wrong. We would like to have this working asap.

**Comment by pieterjanpintens** [comment]
I will rebase my commit on master

**Comment by lukasj** [comment]
once rebased on master, [travis config](https://github.com/eclipse-ee4j/jaxb-ri/blob/master/.travis.yml#L28) can help you

**Comment by lukasj** [comment]
btw: [SNAPSHOTS from master](https://ci.eclipse.org/jaxb-impl/job/jaxb-ri-master-build/) are being published through [oss.sonatype repo](https://oss.sonatype.org/#nexus-search;quick~jaxb-ri)

**Pull request closed without merging**
