### PR TITLE
Backports from master

### PR DESCRIPTION
**Pull request by lukasj**

### CODE REVIEW

**Comment by lukasj** [comment]
@OritMarkus the ECA check is failing for your commit - did you [sign ECA](https://accounts.eclipse.org/user/eca) ?

**Comment by OritMarkus** [comment]
@lukasj Only now

**Comment by lukasj** [comment]
don't see it at [your profile page](https://accounts.eclipse.org/users/oritmarkus), let's give it some time...

**Comment by OritMarkus** [comment]
@lukasj Did you manage?

**Pull request merged**
