### PR TITLE
fix dtd parsing

### PR DESCRIPTION
**Pull request by antoniosanct**
Hi, everyone!

Fighting with a big DTD file I found a bug parsing null references. I wish you can integrate this PR.

The DTD afected is:
https://publication-bdds.apps.epo.org/bdds/bdds-bff-service/prod/api/public/products/19/delivery/472/item/1284/download

Regards,
Antonio.

### CODE REVIEW

**Comment by antoniosanct** [comment]
Another option is transform Block elements attribute from LinkedHashSet to LinkedList to allow duplicated elements, and always generate a default class when element is #PCDATA, at Element clasClass() method. In this way, avoids NPE and JAXB runs correctly.
Regards,
Antonio.

**Comment by antoniosanct** [comment]
Any updates about this?
Thanks a lot! Regards,
Antonio.

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
thanks!

**Pull request merged**
