### PR TITLE
[#1695] Fix parsing of 'tru...' values inconsistent to true boolean

### LINKED ISSUE #1695: DatatypeConverter.parseBoolean converts invalid strings to true
The method `parseBoolean` in `javax.xml.bind.DatatypeConverterImpl` is supposed to convert only the values `"true"` and `"1"` to `true` (while ignoring leading and trailing whitespace). It, however, converts all strings to `true` that start with `"tru"` and are 4-5 characters long. For example:

```
DatatypeConverter.parseBoolean("trux"); // -> true
DatatypeConverter.parseBoolean("truu"); // -> true
DatatypeConverter.parseBoolean("truxx"); // -> true
DatatypeConverter.parseBoolean("truuu"); // -> true
```

This is caused by these segments in `parseBoolean`:
```
case 't':
    String strTrue = "rue";
    do {
        ch = literal.charAt(i++);
    } while ((strTrue.charAt(strIndex++) == ch) && i < len && strIndex < 3);

    if (strIndex == 3) {
        value = true;
    } else {
        return false;
    }
```
and:
```
if (i < len) {
    do {
        ch = literal.charAt(i++);
    } while (WhiteSpaceProcessor.isWhiteSpace(ch) && i < len);
}

if (i == len) {
    return value;
} else {
    return null;
}
```

In the first snippet `value` is assigned `true` also when the loop was left after comparing the third character, because the expression `strTrue.charAt(strIndex++) == ch` was false (that is when there is as mismatch between 'e' and the current character). strIndex will still be 3 (because it is incremented unconditionally).

That explains why `"trux"` is converter to `true`. The second snippet explains why the additional character in `"truxx"` is also ignored. If we haven't read the input completely the second input checks if there is whitespace to ignore. However it also uses an unconditional increment of the reading position, which causes the code to skip over the offending last character. Therefore `i == len` holds and the previously assigned `true` is returned.

### PR DESCRIPTION
**Pull request by laurentschoelens**
Fixes #1695 
Adding test case to validate `_parseBoolean` function

### CODE REVIEW

**Comment by antoniosanct** [comment]
Hi, @laurentschoelens: 

I have some questions about this PR because it could be some mistakes based on another tests at the same project:
- Are using JUnit 4 for any reason? You can extend JUnit 3's TestCase superclass by same manner than other tests that exists at the same project.
- You didn't fix the 'f' case clause. For this reason, unit tests in your own test file, lines 25, 34, 35, 36 and 41, expects null while the correct value would be false, according to use the same solution for 't' case clause.

Regards,
Antonio.

**Comment by laurentschoelens** [comment]
Hi @antoniosanct 

> Hi, @laurentschoelens: 
> 
> I have some questions about this PR because it could be some mistakes based on another tests at the same project:
> - Are using JUnit 4 for any reason? You can extend JUnit 3's TestCase superclass by same manner than other tests that exists at the same project.

Is there any reason to stay to JUnit 3 testing style ? Since JUnit 5 is out for a moment, I would say that the best option would be to start migration to JUnit 5.
I can sure adapt to JUnit 3.

> - You didn't fix the 'f' case clause. For this reason, unit tests in your own test file, lines 25, 34, 35, 36 and 41, expects null while the correct value would be false, according to use the same solution for 't' case clause.

You're right. Since this class is deprecated and behaviour inconsistent, I didnt want to change too much.
Will fix more parseBoolean inconsistent results based on the same PR I did in API with more strict boolean checking : https://github.com/jakartaee/jaxb-api/pull/279

> 
> Regards,
> Antonio.
> 

Regards,
Laurent

**Comment by antoniosanct** [comment]
@laurentschoelens 
I'm agree with you about JUnit 5. My point is to use other PR to improve it.

**Comment by laurentschoelens** [comment]
> @laurentschoelens 
> I'm agree with you about JUnit 5. My point is to use other PR to improve it.

Ok but I didnt add junit4 dependency, it was already in the classpath, no ?

**Comment by lukasj** [comment]
as long as the test runs as part of the build, it does not matter whether it is 3 or 4; 4 is on the classpath already

**Comment by laurentschoelens** [comment]
Let me fix my PR first before merging this one @lukasj

**Comment by laurentschoelens** [comment]
@antoniosanct new commit to be more accurate based on API impl (without throwing any excepion)

**Comment by antoniosanct** [comment]
Hi, @laurentschoelens 
Is it correct to return <null> instead of <false> when it parses other string than <1> or <true>?
Regards,
Antonio!

**Comment by laurentschoelens** [comment]
@antoniosanct missing comment no ? 😄

**Comment by antoniosanct** [comment]
@laurentschoelens 
Sorry, I wanted to say <1> or <true>. Whatever, what's the best result when it parses other value than <1> or <true>, false or null?
Thanks again!
Antonio

**Comment by laurentschoelens** [comment]
In my opinion and in author original spirit, when it parses 0 or false, it should return false, when something else, since not a boolean in xsd representation, that will be null or Exception (in api).
I've just aligned the impl code in jaxb-ri to the same code in api with that difference (null in ri vs exception in api)

**Comment by laurentschoelens** [comment]
In my opinion and in author original spirit, when it parses 0 or false, it should return false, when something else, since not a boolean in xsd representation, that will be null or Exception (in api).
I've just aligned the impl code in jaxb-ri to the same code in api with that difference (null in ri vs exception in api)

**Comment by antoniosanct** [comment]
@laurentschoelens 
OK for me! Thanks a lot for this PR!!

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
