### PR TITLE
Fix generation of the OSGi manifest

### PR DESCRIPTION
**Pull request by arjantijms**

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Review by lukasj — CHANGES_REQUESTED** [review]
the cause is that GF is missing JDK packages in the definition of the `org.osgi.framework.system.packages` property in its `osgi.properties` file. Why do think it is better to keep "fixing" external libraries instead of fixing a GF bug?

**Comment by arjantijms** [comment]
> the cause is that GF is missing JDK packages in the definition of the `org.osgi.framework.system.packages` property in its `osgi.properties` file. Why do you think it is better to keep "fixing" external libraries instead of fixing a GF bug?

You may be on to something there, and it's certainly something to explore. That said, the `<_noimportjava>true</_noimportjava>` is often advised to always add, and many libraries (not just those targeting GlassFish) add the instruction.

See eg: https://academy.jahia.com/documentation/developer/jahia/8/module-development/using-java-11

I agree that blindly adding an instruction because "the internet says so" is not good practice, but it's something to take into account.

**Comment by lukasj** [comment]
> the <_noimportjava>true</_noimportjava> is often advised to always add, and many libraries (not just those targeting GlassFish) add the instruction

Why? I mean - what is the reason behind this instruction being added by other libraries? according to my own research - which may, of course, be wrong - the only valid reason to use this instruction is to keep compatibility with Java SE 8 and OSGi R6. In all other cases, the usage of this instruction is the simplest way to make things working, yet it goes against its intended usage.

as for resources I used:
* https://adapt.to/2018/presentations/adaptto2018-java9-and-osgi-r7-with-apache-felix-and-sling-carsten-ziegeler-karl-pauls.pdf
* https://blog.osgi.org/2018/02/osgi-r7-highlights-java-9-support.html?m=1
* https://bnd.bndtools.org/instructions/noimportjava.html
* https://github.com/eclipse-ee4j/glassfish/blob/master/nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties#L72-L77
* https://www.slideshare.net/mfrancis/osgi-and-java-9-bj-hargrave-ibm

**Comment by dmatej** [comment]
@lukasj Honestly I didn't think of it. After your comment I started experimenting with that, but without success yet. I will tell you soon if there is a way or not. The `_noimportjava` is really fast and reliable at this moment, but let's try the other way.

**Comment by dmatej** [comment]
> @dmatej adding list of packages from https://docs.oracle.com/en/java/javase/11/docs/api/element-list to `osgi.properties` made it work on my end - but that's quick & dirty. Probably better to look for the property definition in the felix/equinox/... itself to get the right set

It is finally the same, the `osgi.properties` are just loaded by GF (`MainHelper` class), then the helper replaces some values (System.properties support). The OSGI platform is chosen by `GlassFish_Platform` property, default is `Felix`. I am afraid that `Knopflerfish` is not even compatible now and `Equinox` would need upgrade and testing, but this issue is not on the table now.

The list of packages set to `org.osgi.framework.system.packages `is then constructed from several other properties with respect to chosen OSGI platform. So perhaps I will just create another property to make it maintainable at least. But thanks for the list, I could not find it.

**Comment by lukasj** [comment]
[jre-11](https://github.com/eclipse-ee4j/glassfish/blob/master/nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties#L366) was the property I have updated during my experiments

**Comment by lukasj** [comment]
btw: by reference to the properties file in felix/... (basically some OSGi runtime) I was referirng to ie [felix definition](https://github.com/apache/felix-dev/blob/master/framework/src/main/resources/default.properties#L133)

**Comment by dmatej** [comment]
It seems the PR can be closed for now.

**Pull request closed without merging**
