### PR TITLE
Fixes #1224. Added gitignore files...

### LINKED ISSUE #1224: Create a .gitignore file for the project.
Let us please reduce the risk of committing/pushing irrelevant IDE-related files into the repo.

### PR DESCRIPTION
**Pull request by lennartj**
Added gitignore file within root and reactor root directories.
This implies both tools and IDEs will use the .gitignore file.

### CODE REVIEW

**Comment by lennartj** [comment]
Unless there is python code in the repository, it makes rather a lot of sense to add it to _gitignore_.
That would permit people to create test and homegrown scripts without fear of getting them checked in.

I will remove the _bin_ directory, though.

**Comment by lennartj** [comment]
All right. All your changes done to the gitignore files.

**Comment by silkentrance** [comment]
why would you need a second .gitignore in the jaxb-ri folder? one at the top level suffices.

**Comment by lennartj** [comment]
IDEs do not use _.gitignore_ files outside of the scope of the reactor, so we need a .gitignore duplicated within the root pom level ... since the root pom is not at the repo root.

**Comment by lukasj** [comment]
closing as there is a conflict and this contains way more than required

**Pull request closed without merging**
